Repository qualabs/dash.js, pull requests merged in 2025-03, with the labels that each got.

#59 Mpd lists/unit test
  src/streaming/controllers/ListMpdController.js
  test/unit/data/dash/manifest_list_mpd.xml
  test/unit/helpers/MPDHelper.js
  test/unit/helpers/VOHelper.js
  test/unit/mocks/ManifestLoaderMock.js
  test/unit/test/streaming/streaming.ListMpdController.js
Labels: unit test

#62 bug fix: some elements of imported period always overrides an element…
  src/dash/DashAdapter.js
  src/streaming/controllers/ListMpdController.js
Labels: bug

#61 Merge mpd level essentaial and suplemental properties to linked periods
  src/dash/DashAdapter.js
  src/streaming/controllers/ListMpdController.js
Labels: bug

#51 [ValidiyExpiration] Update the manifest when the InbandEventStream value attribute is three
  src/core/events/CoreEvents.js
  src/dash/DashAdapter.js
  src/streaming/ManifestLoader.js
  src/streaming/ManifestUpdater.js
  src/streaming/MediaPlayer.js
  src/streaming/controllers/EventController.js
Labels: DON'T MERGE
